### PR TITLE
Make manual (Beat)Pulse control update immediately

### PR DESCRIPTION
**Pull request by Bauumm**
This one is mainly for a few levels in 1.92 that use these effects to an extreme extent, for those I need to be able to set the pulse values more than 240 times per second.

### CODE REVIEW

**Comment by vittorioromeo** [comment]
Hmm, how does this help exactly? Aren't pulse and beatPulse values used 240 times per second anyway?

**Comment by Bauumm** [comment]
Read again
> more than 240 times per second
This helps with some 1.92 levels that rely on some weird effects that happen when this is done (even on low refresh rate monitors).

**Comment by Bauumm** [comment]
An example would be [Foreshock from Imaginative Leftovers](https://www.youtube.com/watch?v=4hPBary8yHE).

**Review by vittorioromeo — APPROVED** [review]
LGTM

**Pull request merged**
